'use strict';

// Declare app level module which depends on views, and components
var app = angular.module('myApp', [
  'ngRoute',
  'myApp.view1',
  'myApp.view2',
  'myApp.version',
    'angular.filter'
]).
config(['$locationProvider', '$routeProvider', function($locationProvider, $routeProvider) {
  $locationProvider.hashPrefix('!');

  $routeProvider.otherwise({redirectTo: '/view1'});
}]);

app.constant('config', {
    gw2AccessToken: "3FDA2B03-EC05-EA4B-9901-7E7854D18CA48A682A20-2E8C-4205-B584-CB32EC4B744D",
});

app.constant('gw2ApiUrls', {
    Root: "https://api.guildwars2.com",
    QueryString: "?access_token=",
    Account: '/v2/account',
    AccountAchievements: '/v2/account/achievements',
    Bank: '/v2/account/bank',
    Dyes: '/v2/account/dyes',
    Finishers: '/v2/account/finishers',
    Inventory: '/v2/account/inventory',
    Masteries: '/v2/account/masteries',
    Materials: '/v2/account/materials',
    Minis: '/v2/account/minis',
    Outfits: '/v2/account/outfits',
    Recipies: '/v2/account/recipes',
    Skins: '/v2/account/skins',
    Titles: '/v2/account/titles',
    Wallet: '/v2/account/wallet',
    AllAchievements: '/v2/achievements/',
    AchievementCategories: '/v2/achievements/categories',
    DailyAchievements: '/v2/achievements/daily',
    TomorrowsDailyAchievements: '/v2/achievements/daily/tomorrow',
    AchievementGroups: '/v2/achievements/groups',
    BackstoryAnswers: '/v2/backstory/answers',
    BackstoryQuestions: '/v2/backstory/questions',
    Build: '/v2/build',
    Characters: '/v2/characters',
    Colors: '/v2/colors',
    Exchange: '/v2/commerce/exchange',
    Coins: '/v2/commerce/exchange/coins',
    Gems: '/v2/commerce/exchange/gems',
    Listings: '/v2/commerce/listings',
    Prices: '/v2/commerce/prices',
    Transactions: '/v2/commerce/transactions',
    Continents: '/v2/continents',
    Currencies: '/v2/currencies',
    Emblems: '/v2/emblem',
    Files: '/v2/files',
    AllFinishers: '/v2/finishers',
    Guild: '/v2/guild/: id',
    GuildLog: '/v2/guild/: id/log',
    GuildMembers: '/v2/guild/:id/members',
    GuildRanks: '/v2/guild/:id/ranks',
    GuildStash: '/v2/guild/:id/stash',
    GuildTeams: '/v2/guild/:id/teams',
    GuildTreasury: '/v2/guild/:id/treasury',
    GuildUpgrades: '/v2/guild/:id/upgrades',
    GuildPermissions: '/v2/guild/permissions',
    GuildSearch: '/v2/guild/search',
    GuildAllUpgrades: '/v2/guild/upgrades',
    Items: '/v2/items',
    ItemStats: '/v2/itemstats',
    Legends: '/v2/legends',
    Maps: '/v2/maps',
    AllMasteries: '/v2/masteries',
    AllMaterials: '/v2/materials',
    AllMinis: '/v2/minis',
    AllOutfits: '/v2/outfits',
    AllPets: '/v2/pets',
    AllProfessions: '/v2/professions',
    Pvp: '/v2/pvp',
    PvpAmulets: '/v2/pvp/amulets',
    PvpGames: '/v2/pvp/games',
    PvpRanks: '/v2/pvp/ranks',
    PvpSeasons: '/v2/pvp/seasons',
    PvpLeaderboards: '/v2/pvp/seasons/leaderboards',
    PvpStandings: '/v2/pvp/standings',
    PvpStats: '/v2/pvp/stats',
    Quaggans: '/v2/quaggans',
    AllRecipes: '/v2/recipes',
    SearchRecipies: '/v2/recipes/search',
    Skills: '/v2/skills',
    AllSkins: '/v2/skins',
    Specializations: '/v2/specializations',
    Stories: '/v2/stories',
    StorySeasons: '/v2/stories/seasons',
    AllTitles: '/v2/titles',
    TokenInfo: '/v2/tokeninfo',
    Traits: '/v2/traits',
    Worlds: '/v2/worlds',
    Wvw: '/v2/wvw',
    WvwAbilities: '/v2/wvw/abilities',
    WvwMatches: '/v2/wvw/matches',
    WvwObjectives: '/v2/wvw/objectives',
    WvwRanks: '/v2/wvw/ranks',
});